---
services:
  - docker

env:
  - distribution: centos
    version: "7"
  - distribution: centos
    version: "6"
  - distribution: fedora
    version: "28"
  - distribution: fedora
    version: "27"
  - distribution: fedora
    version: "26"

before_install:
  # Build docker container
  - 'sudo docker pull diodonfrost/${distribution}-${version}-ansible:latest'

script:
  - container_id=$(mktemp)

  # Run container and mount ansible role with it
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/roles/ansible-role-fail2ban:ro diodonfrost/${distribution}-${version}-ansible:latest > "${container_id}"'

  # Check syntax
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/ansible-role-fail2ban/tests/test.yml --syntax-check'

  # Run ansible playbook
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/ansible-role-fail2ban/tests/test.yml'

  # Test indempotence
  - >
    sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/ansible-role-fail2ban/tests/test.yml
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # Test role
  - 'inspec exec tests/inspec -t docker://$(cat ${container_id})'

  # Delete container
  - 'sudo docker rm -f "$(cat ${container_id})"'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
