---
# Install and configure fail2ban

- name: Update apt cache
  apt:
    update_cache: yes
  changed_when: false
  when: ansible_os_family == "Debian"

- name: Install fail2ban
  package:
    name: "{{ fail2ban_package }}"
    state: present

- name: get fail2ban version
  shell: fail2ban-server -V 2>&1 | head -n 1 | sed -r 's/.*([0-9].[0-9]).*/\1/g'
  args:
    executable: /bin/sh
  changed_when: false
  register: fail2ban_version
  check_mode: no

- name: Use fail2ban template v0.8.0
  set_fact:
    jail_template: jail-v9.j2
  when: fail2ban_version.stdout >= '9.0' and not jail_template

- name: Use fail2ban template v0.9.0
  set_fact:
    jail_template: jail-v8.j2
  when: fail2ban_version.stdout >= '8.0' and not jail_template

- name: Configure fail2ban
  template:
    src: "{{ jail_template }}"
    dest: "{{ fail2ban_config }}"
    owner: "{{ fail2ban_config_owner }}"
    group: "{{ fail2ban_config_group }}"
    mode: 0600
  notify:
    - "(Handler: All Linux/Unix OSs) Restart fail2ban"

- name: Configure jail
  template:
    src: jail.j2
    dest: "{{ fail2ban_jail }}"
    owner: "{{ fail2ban_config_owner }}"
    group: "{{ fail2ban_config_group }}"
    mode: 0600
  notify:
    - "(Handler: All Linux/Unix OSs) Restart fail2ban"

- name: Manage fail2ban service
  service:
    name: "{{ fail2ban_service }}"
    state: started
    enabled: yes
